#!/bin/sh

# Cloudant credentials generated by bluemix
CLOUDANT_USERNAME=6163d225-2362-46ba-8608-c0c58cac2509-bluemix
CLOUDANT_PASSWORD=93cd9a5054e980352e3cb2ec0a50346052e6fca0a48b04cf33689d72b26adcbb

# name of database
DATABASE=intellum

# input validation
if [ -z "${CLOUDANT_USERNAME}" ]; then
    echo "Please provide your CLOUDANT_USERNAME."
    exit
fi
if [ -z "${CLOUDANT_PASSWORD}" ]; then
    echo "Please provide your CLOUDANT_PASSWORD."
    exit
fi

# credentials to post data to cloudant
AUTH="$(python -c 'import base64; print base64.urlsafe_b64encode("'${CLOUDANT_USERNAME}':'${CLOUDANT_PASSWORD}'")')"
ACURL="curl -s --proto '=https' -iv -g -H 'Authorization: Basic ${AUTH}'"
HOST="https://${CLOUDANT_USERNAME}.cloudant.com"

# dynamically generate security file for cloudant
cat > security.json << EOF
{
  "cloudant": {
    "${CLOUDANT_USERNAME}": [
      "_reader",
      "_writer",
      "_admin",
      "_replicator"
    ],
    "nobody": ["_reader"]
  }
}
EOF

# Places
eval ${ACURL} -H "Content-Type:application/json" -d @security.json -vX PUT '${HOST}/gb_boards/_security'
eval ${ACURL} -H "Content-Type:application/json" -d @places-design.json -vX PUT '${HOST}/intellum/_design/places'
